"use client";

import React from 'react';
import { Shield, FileText, Scale, Lock, AlertCircle, Info } from 'lucide-react';

export default function TermsOfServicePage() {
  const lastUpdated = "March 18, 2026";

  return (
    <div className="max-w-4xl mx-auto space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-700">
      {/* Header Section */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 pb-8 border-b border-slate-200 dark:border-slate-800">
        <div className="space-y-4">
          <div className="flex items-center gap-2">
            <span className="bg-indigo-600 text-[10px] font-black text-white px-2 py-0.5 rounded-full tracking-widest uppercase">Legal Documentation</span>
            <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">v1.4.2</span>
          </div>
          <h1 className="text-4xl font-black text-slate-900 dark:text-white tracking-tighter flex items-center gap-3">
            <Shield className="w-10 h-10 text-indigo-500" />
            Terms of Service
          </h1>
          <p className="text-slate-500 font-medium italic text-sm tracking-tight border-l-2 border-indigo-500/20 pl-4 max-w-2xl">
            Governing the use of Lifestyle Machine's predictive AI, voice interfaces, and lifestyle guidance services across all platforms.
          </p>
        </div>
        <div className="text-right">
          <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">Last Updated</p>
          <p className="text-sm font-black text-slate-900 dark:text-white">{lastUpdated}</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-12 gap-10">
        {/* Navigation / Quick Links */}
        <div className="md:col-span-4 space-y-4">
          <div className="sticky top-24 space-y-1 bg-white dark:bg-slate-900/50 p-4 rounded-2xl border border-slate-200 dark:border-slate-800">
             <h3 className="text-[10px] font-black uppercase text-slate-400 tracking-widest mb-4 px-2">Table of Contents</h3>
             <QuickLink icon={FileText} label="Nature of Service" active />
             <QuickLink icon={Scale} label="Limitation of Liability" />
             <QuickLink icon={Lock} label="Data & Consent" />
             <QuickLink icon={AlertCircle} label="Content Safety" />
             <QuickLink icon={Info} label="Refund Policy" />
          </div>
        </div>

        {/* Content Section */}
        <div className="md:col-span-8 space-y-12 text-slate-600 dark:text-slate-400 leading-relaxed font-medium">
          
          <section className="space-y-4">
            <h2 className="text-xl font-black text-slate-900 dark:text-white tracking-tight flex items-center gap-2">
              <span className="w-2 h-2 bg-indigo-500 rounded-full" />
              1. Nature of the Service
            </h2>
            <p>
              Lifestyle Machine is an AI-powered entertainment platform providing daily insights, astrology, palm reading, and face reading via voice and text interfaces.
            </p>
            <div className="bg-amber-50 dark:bg-amber-500/10 border border-amber-200 dark:border-amber-500/20 p-6 rounded-2xl">
               <div className="flex gap-4 items-start">
                  <AlertCircle className="w-5 h-5 text-amber-600 dark:text-amber-500 shrink-0 mt-0.5" />
                  <div>
                    <p className="text-xs font-black text-amber-900 dark:text-amber-400 uppercase tracking-widest mb-2">Notice for Users</p>
                    <p className="text-sm text-amber-800 dark:text-amber-200/80 font-bold leading-relaxed">
                      All results generated by Lifestyle Machine are for entertainment and lifestyle insight only. They do not constitute professional, medical, financial, or legal advice.
                    </p>
                  </div>
               </div>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-black text-slate-900 dark:text-white tracking-tight flex items-center gap-2">
              <span className="w-2 h-2 bg-indigo-500 rounded-full" />
              2. User Consent and Biometrics
            </h2>
            <p>
              By using our Palm Reading and Face Reading features, you explicitly consent to the processing of your uploaded images. 
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Images are used solely for generating lifestyle insights.</li>
              <li>We do not store biometric data to identify individuals.</li>
              <li>Files are retained for a limited time for processing and quality monitoring.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-black text-slate-900 dark:text-white tracking-tight flex items-center gap-2">
              <span className="w-2 h-2 bg-indigo-500 rounded-full" />
              3. Subscriptions and Payments
            </h2>
            <p>
              Users may access certain features for free (subject to daily limits) or purchase Premium Subscriptions and Report Packages.
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
               <div className="bg-slate-50 dark:bg-slate-800/50 p-6 rounded-2xl border border-slate-100 dark:border-slate-800">
                  <h4 className="text-[10px] font-black uppercase text-indigo-500 mb-2">Premium Plan</h4>
                  <p className="text-sm font-bold text-slate-900 dark:text-white">$3 / Month</p>
                  <p className="text-[10px] mt-1 text-slate-500">Auto-renewing subscription via Wing Bank.</p>
               </div>
               <div className="bg-slate-50 dark:bg-slate-800/50 p-6 rounded-2xl border border-slate-100 dark:border-slate-800">
                  <h4 className="text-[10px] font-black uppercase text-indigo-500 mb-2">Credit Packages</h4>
                  <p className="text-sm font-bold text-slate-900 dark:text-white">Starting at $1</p>
                  <p className="text-[10px] mt-1 text-slate-500">Non-refundable credits for one-time reports.</p>
               </div>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-black text-slate-900 dark:text-white tracking-tight flex items-center gap-2">
              <span className="w-2 h-2 bg-indigo-500 rounded-full" />
              4. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, Lifestyle Machine and its affiliates shall not be liable for any indirect, incidental, or consequential damages resulting from the use of AI-generated insights. Predictions made by the system are for entertainment only.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-black text-slate-900 dark:text-white tracking-tight flex items-center gap-2">
              <span className="w-2 h-2 bg-indigo-500 rounded-full" />
              5. Content Safety
            </h2>
            <p>
              Users are prohibited from using the service to generate harmful, discriminatory, or illegal content. We reserve the right to suspend accounts that violate our safety guidelines or attempt to exploit the AI orchestration layer.
            </p>
          </section>

          <div className="pt-10 border-t border-slate-200 dark:border-slate-800 text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] text-center">
            &copy; 2026 Lifestyle Machine Operations Cluster. All Rights Reserved.
          </div>
        </div>
      </div>
    </div>
  );
}

function QuickLink({ icon: Icon, label, active = false }: any) {
  return (
    <div className={`flex items-center gap-3 px-4 py-3 rounded-xl text-xs font-bold transition-all cursor-pointer ${
      active 
      ? 'bg-indigo-600/10 text-indigo-600 dark:text-indigo-400' 
      : 'text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800'
    }`}>
      <Icon className={`w-4 h-4 ${active ? 'text-indigo-600' : 'text-slate-400'}`} />
      {label}
    </div>
  );
}
